trigger:
  branches:
    include:
      - main

# Use self-hosted agent pool
pool:
  name: Default  # Ensure the agent is assigned to this pool

steps:
  # Install Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Install Dependencies (Windows & Linux Compatible)
  - script: |
      python -m venv venv
      if "%AGENT_OS%" == "Windows_NT" (
        call venv\Scripts\activate
      ) else (
        source venv/bin/activate
      )
      pip install -r src/requirements.txt
    shell: cmd  # Ensures the correct shell is used in Windows
    displayName: 'Install dependencies'

  # Run Flask App
  - script: |
      python src/app.py &
    shell: cmd
    displayName: 'Run Flask App'
