trigger:
  branches:
    include:
      - main  # Run pipeline when code is pushed to 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu agent

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r src/requirements.txt
    displayName: 'Install dependencies'

  - script: |
      source venv/bin/activate
      python src/app.py &
    displayName: 'Run Flask App'
