pool:
  name: Default  # Use the agent pool where your self-hosted agent is running

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r src/requirements.txt
    displayName: 'Install dependencies'

  - script: |
      source venv/bin/activate
      python src/app.py &
    displayName: 'Run Flask App'
