trigger:
  branches:
    include:
      - main

# Use self-hosted agent
pool:
  name: Default  # Ensure the agent is assigned to this pool

steps:
  # Checkout the code
  - checkout: self
    displayName: 'Checkout Repository'

  # Install Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Install Dependencies (Windows & Linux Compatible)
  - script: |
      python -m venv venv
      if "%AGENT_OS%" == "Windows_NT" (
        call venv\Scripts\activate
      ) else (
        source venv/bin/activate
      )
      pip install --upgrade pip
      pip install -r src/requirements.txt
    displayName: 'Install Dependencies'

  # Run Flask App
  - script: |
      if "%AGENT_OS%" == "Windows_NT" (
        call venv\Scripts\activate
      ) else (
        source venv/bin/activate
      )
      python src/app.py
    displayName: 'Run Flask App'
